### ISSUE TITLE
Error in scrapping

### ISSUE THREAD

**Issue by dimasciput** [kartoza/feti#275]
I'm trying to scrapping from staging server, and I got this error : 

```
GETTING CAMPUSS AND PROVIDE IN http://ncap.careerhelp.org.za/
----------------------------------------------------------
processing page 1
found : Boland TVET College - Caledon ----------------------------------------
b"provider : {'website': 'http://www.bolandcollege.com', 'primary_institution': 'Boland TVET College '}"
b"campus : {'campus': ' Caledon'}"
b"address : {'address_line_1': 'College Street, Caledon', 'town': 'Western Cape', 'phone': '0282123270', 'postal_code': 7230}"
generate campus index start
generate campus index finish
Traceback (most recent call last):
  File "/home/web/django_project/feti/models/campus.py", line 178, in save
    self.address_fk = self.address
  File "/usr/local/lib/python3.4/site-packages/django/db/models/fields/related.py", line 521, in __set__
    setattr(value, field.attname, related_pk[index])
AttributeError: 'NoneType' object has no attribute 'campus_fk_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/web/django_project/feti/management/commands/scraping_campus.py", line 139, in handle
    camp = create_campus(campus, prov)
  File "/home/web/django_project/feti/management/commands/scraping_campus.py", line 36, in create_campus
    campus.save()
  File "/home/web/django_project/feti/models/campus.py", line 181, in save
    except self.address.DoesNotExist:
AttributeError: 'NoneType' object has no attribute 'DoesNotExist'
Makefile:299: recipe for target 'scraping' failed
make: *** [scraping] Error 1

```

**Comment by dimasciput** [comment]
@meomancer , Got another error :

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/web/django_project/feti/management/commands/scraping_course.py", line 123, in handle
    create_course(course)
  File "/home/web/django_project/feti/management/commands/scraping_course.py", line 26, in create_course
    national_learners_records_database=int(data['id']))
  File "/usr/local/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
feti.models.course.MultipleObjectsReturned: get() returned more than one Course -- it returned 2!
make: *** [scraping] Error 1
```
